services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pipeline
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: ./Health.Pipeline.Api
    ports:
      - "5005:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=pipeline;Username=pipeline_user;Password=password
    depends_on:
      - db

volumes:
  db-data:
